language: python
python:
 - "2.7"
install: "pip install -r requirements.txt"
script: "python manage.py test"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libffi-dev libffi6
